
services:
  laravel:
    build:
      context: ./API
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hotel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

