services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'HotelBDD'
      MYSQL_USER: 'Benawi'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - 'api:/var/lib/mysql'
    ports:
      - '3307:3306'

  app:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: "mysql"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "HotelBDD"
      DB_USERNAME: "Benawi"
      DB_PASSWORD: "password"
volumes:
  api:
